import { Router } from "express";
import { TripController } from "./controller/trip.controller";
const routes = Router();
const tripController = new TripController();
routes.get("/trip/:uuid?", tripController.getTripByUuid);
routes.get("/trips/:propos?", tripController.getAllTrips);
routes.post("/trip/", tripController.createTrip);
routes.put("/trip", tripController.updateTripByUuid);
routes.delete("/trip/:uuid?", tripController.deleteTripByUuid);
export default routes;
